run:
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt

linters-settings:
  govet:
    check-shadowing: true
  gofmt:
    simplify: true
