version: "3.9"

services:
  db:
    image: postgres:15
    container_name: budget-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: budget
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: budget
    ports:
      - "5432:5432"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U budget -d budget"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
